name: llm-rag
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11.10
  - pip
  - datasets=3.2.0
  - faiss-cpu=1.9.0
  - flask=3.1.0
  - Flask-Caching=2.3.0
  - google-generativeai=0.8.4
  - ipython=8.31.0
  - jupyter=1.1.1
  - langchain=0.3.17
  - langchain-chroma=0.2.1
  - langchain-community=0.3.16
  - langchain-huggingface=0.1.2
  - langchain-openai=0.3.3
  - langchainhub=0.1.21
  - matplotlib=3.10.0
  - numpy=1.26.4
  - pandas=2.2.3
  - python-dotenv=1.0.1
  - ragas=0.2.12
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - unstructured=0.16.17

  - pip:
    - evaluate==0.4.3
    - rouge_score==0.1.2
    - torch==2.6.0